"""create user table

Revision ID: 185c1aab8aef
Revises: 1614da8c5ded
Create Date: 2023-01-15 23:25:30.046850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '185c1aab8aef'
down_revision = '1614da8c5ded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo_tb', sa.Column('name', sa.String(), nullable=False, primary_key=True))
    op.add_column('userinfo_tb', sa.Column('passwd', sa.String(), nullable=False))
    op.add_column('userinfo_tb', sa.Column('createT', sa.DateTime(), nullable=True, default = datetime.utcnow()))
    op.drop_column('userinfo_tb', 'username')
    op.drop_column('userinfo_tb', 'password')
    op.drop_column('userinfo_tb', 'create_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo_tb', sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('userinfo_tb', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('userinfo_tb', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False, primary_key=True))
    op.drop_column('userinfo_tb', 'createT')
    op.drop_column('userinfo_tb', 'passwd')
    op.drop_column('userinfo_tb', 'name')
    # ### end Alembic commands ###
